server:
  port: 8080
  error:
    include-message: always

spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            token-uri: "http://localhost:8888/token"
        registration:
          infinum:
            provider: spring
            client-id: test_client_id
            client-secret: test_client_secret
            authorization-grant-type: client_credentials